<?php
/**
 * @file
 * Code for the social media autopost types feature.
 */

include_once 'social_media_types.features.inc';

/**
 * Implements hook_field_property_data_alter().
 */
function social_media_types_field_property_data_alter(&$data) {
  // field_facebook_scheduled_publish should be translated to scheduled_publish_time
  if (isset($data['field_facebook_scheduled_publish'])) {
    $data['field_facebook_scheduled_publish'] = 'scheduled_publish_time';
  }
}
